title: "Aya"
lang: tr-TR
encoding: utf-8
description: "fly me to the moon aya"
copyright: "stay with me asu"

url: "https://yyzeka.github.io"
baseurl: "/aya"

email: "miyawkity@gmail.com"

darkmode: true
typosize: true
home-posts-limit: 5

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: PQuod/simply-cyan-theme



